### ISSUE TITLE
Failed to run diagnostics: ! in callr subprocess

### ISSUE THREAD

**Issue by Mayur1009** [quarto-dev/quarto-nvim#84] opened 2023-08-21 17:49 UTC
Hi, Amazing work with the plugin. It works well for the most part. I have been getting this error,  always on the first line of the quarto document. 

>  Failed to run diagnostics: ! in callr subprocess.
Caused by error: 
! Linter 'object_length_linter' failed in /path/to/doc1.qmd.otter.R: path[1]="/path/to/doc1.qmd.otter.R": No such file or directory

I am fairly new to Neovim and don't know much about debugging such problems.

**Comment by jmbuhr** [comment] 2023-08-22 09:42
Can you provide a minimal example in which this happens for you? I can't reproduce this behavior in https://github.com/jmbuhr/quarto-nvim-kickstarter using the recommended lintr configuration: https://github.com/quarto-dev/quarto-nvim#r-diagnostics-configuration

![image](https://github.com/quarto-dev/quarto-nvim/assets/17450586/143c45b9-f7e4-4d4c-80d1-e8a9c7a35979)

**Comment by Mayur1009** [comment] 2023-08-22 13:07
I did a fresh install of the [quato-nvim-kickstarter](https://github.com/jmbuhr/quarto-nvim-kickstarter) config. It installed all the LSP servers and Mason stuff needed. I added the `.lintr` file in my home directory, as mentioned. Also added the config for `marksman`. 

Now I created a new file named `my.qmd` and added some code blocks, etc. Then when I save the file I get the above-mentioned error.

![Screenshot_20230822_183140](https://github.com/quarto-dev/quarto-nvim/assets/31240856/50514b01-ffcc-4339-b284-514070443df0)

Error Message:
![Screenshot_20230822_183635](https://github.com/quarto-dev/quarto-nvim/assets/31240856/7575216a-013a-4f8c-8282-ee8a677b3e86)

**Comment by jmbuhr** [comment] 2023-08-22 15:15
very curious, what version of lintr do you have?

It's understandable that lintr wouldn't find the file, since the hidden buffers I use for diagnostics and code completion are not actually files, but it shouldn't look for them either.

**Comment by Mayur1009** [comment] 2023-08-22 16:05
If you mean the `lintr` installed through R `install.packages()`, it is the latest one `3.1.0`.

**Comment by jmbuhr** [comment] 2023-08-23 08:15
I'm also on that version. Then I don't know what the difference in our setups is. What you can try for now is also disabling the offending `object_length_linter` in the `.lintr` config.

**Comment by joelewis101** [comment] 2024-01-03 12:08
Hi,

Thanks so much for these plugins. Sorry to say that I have the same error as above on the quarto kickstarter config with R code blocks. Code completion for r works in quarto r code blocks but diagnostcis don't, with the same error as above.  Disabling `object_length_linter` in the `.lintr` config still fails with:

```
 Diagnostics:
 Failed to run diagnostics: ! in callr subprocess.
 Caused by error:
 ! Linter 'object_name_linter' failed in /Users/joelewis/tmp/test.qmd.otter.R: path[1]="/Users/joelewis/tmp/test.qmd.
 otter.R": No such file or directory
```
Diagnostics work as expected in .r files

I think it must be something to do specifically with the R languagesever or lintR as python and lua code chunks have diagnostics displayed as expected.

![image](https://github.com/quarto-dev/quarto-nvim/assets/29750697/1260058b-40ae-4a2c-a3fe-1816f1fdc3c4)


I'm on macos sonoma 14.2.1, R v4.3.1 with lintR 3.1.1, r languageserver 0.3.16 and lastest (as of today) versions of quarto and otter, neovim v0.9.4

Sorry to reopen an old issue, happy to submit a new issue if helpful.

**Comment by jmbuhr** [comment] 2024-01-04 14:02
The feature is merged now, but not enabled by default.

**Closed by jmbuhr** 2024-01-04 14:02 UTC
Labels: bug, reproduction pending

**Comment by joelewis101** [comment] 2024-01-05 09:40
Brilliant! Can confirm is now working for me for R in .qmd code block with `write_to_disk = true` - thanks so much for a super speedy response and update.
